name: ldm
channels:
  - nvidia/label/cuda-11.6.2
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch=1.12.1
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
      - sanic==22.6.2
      - git+https://github.com/huggingface/accelerate.git@main
      - git+https://github.com/huggingface/diffusers.git@main
      - clip
      - torchsde
      - k-diffusion==0.0.12
      - basicsr
      - fairscale
      - invisible-watermark
      - numpy
      - omegaconf
      - piexif
      - Pillow
      - pytorch_lightning==1.9.2
      - realesrgan
      - scikit-image>=0.19.3
      - timm==0.4.12
      - transformers==4.26.0
      - scipy==1.10.0
      - requests_futures==1.0.0
      - einops
      - jsonmerge
      - clean-fid
      - resize-right
      - torchdiffeq
      - kornia
      - lark
      - functorch
      - jupyterlab
      - ipywidgets
      - jupyter-archive
      - GitPython
      - inflection
      - albumentations==1.3.0
      - bitsandbytes==0.35.0
      - ftfy==6.1.1
      - spacy==3.5.0
      - gfpgan==1.3.8
      - tensorboard==2.12.0
      - tqdm
      - open_clip_torch
      - safetensors
      - huggingface_hub
      - opencv-contrib-python
      - controlnet-aux
      - triton==2.0.0.dev20221202
      - pyre-extensions==0.0.23
      - boto3==1.26.57
      - botocore==1.29.57
      - pytest==7.2.1
      - pytest-cov==4.0.0
      - datasets==2.8.0
